remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: noahats' CyberSecurity Portfolio
description: Projects I have been working on.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
